namespace ProjectScript.Enums
{
    public enum DigimonAttribute
    {
        Vaccine,
        Data,
        Virus,
        Free,
        Variable,
        Unknown,
        NoAttribute,
    }
    public enum DigimonStage
    {
        InTraining,
        Rookie,
        Champion,
        Ultimate,
        Mega
    }
    public enum DigimonField
    {
        NatureSpirits,
        DeepSavers,
        NightmareSoldiers,
        WindGuardians,
        MetalEmpire,
        Unknown,
        DarkArea,
        VirusBusters,
        DragonsRoar,
        JungleTroopers,
        NoField,
    }
    public enum DigimonCrest
    {
        Courage,
        Friendship,
        Love,
        Knowledge,
        Sincerity,
        Reliability,
        Light,
        Hope,
        Miracles,
        Kindness,
    }
    public enum DigimonType
    {
        Lesser,
        Reptile,
        Dinosaur,
        Cyborg,
        DragonMan,
        Beast,
        BeastMan,
        Chick,
        GiantBird,
        BirdMan,
        HolyBeast,
        Insect,
        MarineBeast,
        Plesiosaur,
        Plant,
        Fairy,
        Mammal,
        Angel,
        Archangel,
        Seraph,
        HolyDragon,
        Ceratops,
        Flame,
        Ankylosaur,
        AquaticMammal,
        AncientFish,
        Mollusk,
        AquaticBeastMan,
        Mutation,
        Aquatic,
        IceSnow,
        Ore,
        Amphibian,
        Composite,
        Invade,
        DemonMan,
        Mineral,
        Machine,
        Undead,
        EvilDragon,
        SmallDevil,
        Ghost,
        AncientBeast,
    }
}
